pipeline {

    agent any

    stages {

        stage('Clone Repository') {

            steps {

                git 'https://github.com/yourusername/devops-cicd-kubernetes-aws.git'

            }

        }

        stage('Build Docker Image') {

            steps {

                sh 'docker build -t yourdockerhub/devops-demo app/'

            }

        }

        stage('Push Docker Image') {

            steps {

                sh 'docker push yourdockerhub/devops-demo'

            }

        }

        stage('Deploy to Kubernetes') {

            steps {

                sh 'kubectl apply -f kubernetes/'

            }

        }

    }

}
